autoscaling:
  minReplicas: 2

# env defines the environment variables that will be declared in the pod
env:
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    - name: OrchestratorType
      value: "K8S"
    - name: IsClusterEnv
      value: "True"
