apiVersion: v1
kind: Service
metadata:
  name: { { .Values.app.svc.projectone } }
  labels:
    app: { { template "project-one.name" . } }
    chart: { { template "project-one.chart" . } }
    release: { { .Release.Name } }
    heritage: { { .Release.Service } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: { { template "project-one.name" . } }
    release: { { .Release.Name } }
