steps:
- checkout: none
- task: HelmInstaller@1
  displayName: 'install helm'
  inputs:
    helmVersionToInstall: $(helmVersion)
- download: ci-pipeline
  artifact: build-artifact
- bash: |
   az login \
        --service-principal \
        -u $(aksSpId) \
        -p '$(aksSpSecret)' \
        --tenant $(aksSpTenantId)
    az aks get-credentials \
        -n $(aks) \
        -g $(rg)
    echo $(registryPassword) | helm registry login $(registryServerName) --username $(registryLogin) --password-stdin
    helmChartVersion=$(jq .helmChartVersion $(pipeline.workspace)/ci-pipeline/build-artifact/variables.json -r)
    helm chart pull $(registryServerName)/charts/$(projectName):$helmChartVersion
    helm chart export $(registryServerName)/charts/$(projectName):$helmChartVersion --destination $(pipeline.workspace)/install
    helm upgrade \
        --namespace $(k8sNamespace) \
        --create-namespace \
        --install \
        --wait \
        --version $helmChartVersion \
        --set image.repository=$(registryServerName)/$(projectName) \
        -f $(pipeline.workspace)/ci-pipeline/build-artifact/deploy/k8s/helm/app.yaml \
        -f $(pipeline.workspace)/ci-pipeline/build-artifact/deploy/k8s/helm/inf.yaml \
        -f $(pipeline.workspace)/ci-pipeline/build-artifact/deploy/k8s/helm/inf-prod.yaml \
        -f $(pipeline.workspace)/ci-pipeline/build-artifact/deploy/k8s/helm/$(projectName)/values-prod.yaml \
        $(projectName) \
        $(pipeline.workspace)/install/$(projectName)
  failOnStderr: true
  displayName: 'deploy helm chart'
